---
- name: check alertmanager configure files
  command: "{{ alertmanager_bin_path }}/amtool check-config {{ alertmanager_etc_path }}/alertmanager.yml"

- name: systemd daemon reload
  systemd:
    daemon_reload: true

- name: restart alertmanager service
  systemd: name=alertmanager state=restarted daemon_reload=yes

- name: reload alertmanager service
  systemd: name=alertmanager state=reloaded
