---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-alertmanager-role-EL-7
    image: centos:7
  - name: test-alertmanager-role-ubuntu-xenial
    image: ubuntu:xenial
  - name: test-alertmanager-role-ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
